name: mooncake
description: A decentralized microblogging application based on Desmos
version: 0.4.0+04006

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  alan:
    git:
      url: git://github.com/alan-sdk/alan.dart.git
      ref: cosmos-v0.38.0
  bip39:
  carousel_slider:
  cached_network_image:
  collection:
  crypto:
  dependencies:
  dynamic_theme:
  encrypt:
  emoji_picker:
  equatable:
  firebase_analytics:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_email_sender:
  flutter_emoji:
  flutter_local_notifications:
  flutter_markdown:
  flutter_secure_storage:
  flutter_staggered_grid_view:
  font_awesome_flutter:
  gradient_widgets:
  graphql:
  http:
  image_picker:
  intl:
  json_annotation:
  local_auth:
  meta:
  mime_type:
  package_info:
  path_provider:
  password_strength:
  pointycastle:
  recase:
  rxdart:
  sembast:
  sentry:
  share:
  shared_preferences:
  timeago:
  url_launcher:

dev_dependencies:
  bloc_test:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable:
  mockito:
  mock_web_server:
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Mooncake
      fonts:
        - asset: assets/fonts/mooncake-icons.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
